version: '3.1'
services:
  next-auth-poc:
    image: next-auth-poc:latest
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=docker-compose-secret
      - NEXTAUTH_URL=http://docker-compose:3000/api/auth
      - DISCORD_CLIENT_ID=abc
      - DISCORD_CLIENT_SECRET=123
    # env_file:
    #   - path: './env-configs//env.dev'